### ISSUE TITLE
How can I change the asctime format?

### ISSUE THREAD

**Issue by jclosure** [laysakura/rainbow_logging_handler#15]
The default date_format is **HH:MM:SS**.  I need what is the default logger date_format, i.e. **_%Y-%m-%d %H:%M:%S_** with milliseconds as _.%(msecs)03d_.

**Comment by jclosure** [comment]
Figured it out.  Just set `datefmt=None`.  This will cause it to default.  In my case, since I'm using a yaml file, I can just not set the datefmt value to pass it `None`.

```yaml
handlers:
  colored:
    class: rainbow_logging_handler.RainbowLoggingHandler
    datefmt:
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
```
